### ISSUE TITLE
Using CSS variables with postCSS

### ISSUE THREAD

**Issue by madebyreformat** [twbs/rfs#139]
I'm using PostCSS with Parcel bundler but am having trouble using :root CSS variables

```
:root {
  --font-xl: 24px;
}

p  {
  responsive-font-size: var(--font-xl); /* doesn't work */
  responsive-font-size: --font-xl; /* doesn't work */
}
```

It's simple to do with SASS but im not sure it's possible with CSS variables, any ideas?

**Comment by MartijnCuppens** [comment]
RFS can't handle css variables because it calculates the appropriate font sizes based on the value which is passed and than renders the appropriate values and media queries in css.

This will be fixed in `v9` which will work on [a different way](https://github.com/twbs/rfs/issues/119), but since there's not so much browsers support for the `min()` function which is needed, the next version can not be released yet.

**Comment by MartijnCuppens** [comment]
Version 9 just launched, and this version has support for CSS variables, have a look at https://codepen.io/MartijnCuppens/pen/JgRYaw?editors=1100 for a demo
