### ISSUE TITLE
Allowing multiple font sizes to resize from/to?

### ISSUE THREAD

**Issue by antonkor** [twbs/rfs#162]
I've read some of your other comments on this subject but I thought i would ask. How difficult would it be to add a second parameter to the mixin?

this isn't exactly like the mobile first suggestion someone else mentioned, this would just allow you to control you min/max sizes for each element you're trying to style.

For example:
@include font-size(24px,135px);

The first argument is for the minimum breakpoint's font size (being able to configure this like the max would be awesome) and the 2nd argument is for the maximum breakpoint's font size (what you already have, ie, 1200px).

Right now i'm just overriding the @include font-size(135px); with a mobile only mixin i use:

.h2 {
        
        @include font-size(135px);

        @include mobile-only {
            font-size: 43px;
        }
        
}

Kinda dirty but it works well enought. It breaks the responsive nature of RFS on mobile but it's a compromise I'm willing to live with for now. Just checking to see if you have a better solution.

**Comment by MartijnCuppens** [comment]
The purpose of RFS is to automate the rescaling. If this feature is added, some people will use it, while others stick to the way RFS is meant to work. 

I don't want people will start using the min/max way over the automated way just because it feels more natural to what they are used to work with.

---

### So what alternatives do we have?

- RFS is supported within media queries, so with the example above you could do something like:
```scss
.h2 {
    @include font-size(135px);

    @include mobile-only {
	    @include font-size(43px);
    }
}
```
**Watch out:** `v9` switched to a mobile-first approach using `min-width` instead of `max-width`, so you might need to switch the mode to `"max-media-query"`
https://github.com/twbs/rfs/blob/bad76be6ab73e476b6f91199405362e17bac21da/scss.scss#L37-L38
- RFS is configurable, by tweaking the factor you can achieve the rescaling you want
- If none of these solutions fits your needs, you might have a look at this article which uses a mixin what does exactly what you describe: https://css-tricks.com/snippets/css/fluid-typography/#article-header-id-0

**Comment by antonkor** [comment]
@MartijnCuppens thanks for the response! I like the min-width change, had to disable bootstraps RFS import and use your standalone version. 

I've tried your alternative solution, but it didnt do what i had hoped it would. 

I've also tried tweaking the factor option but since im going from a huge font like 135px down to a small font such as 43 i couldn't get it to go down that low automatically even with a factor of 1000. 

i'll just stick to my hacky way for now.. all the designers i work with insist i have exact font sizes on mobile so all my attempts to get factor all i could get was something like 60ish px. Your mixin will save me tons of time sizing out the tablet views.

thanks for your work on this!
