### ISSUE TITLE
rfs in styled-components 

### ISSUE THREAD

**Issue by masimay** [twbs/rfs#209]
is there a way to use **rfs** in **styled-components** ?

**Comment by MartijnCuppens** [comment]
No idea, I've never used styled-components myself. RFS is also a PostCSS plugin, so if styled-components supports these plugins, you can.

**Comment by supposedly** [comment]
Basically, RFS is a bunch of logic whose job is to output CSS, and `styled-components`'s job is to take CSS and do stuff with it under the hood. In fact, `styled-components` doesn't even need to know RFS exists here, because all you need to do is find some way to stick RFS's output directly into `styled-components`'s input. And, happily enough, the only SASS features RFS uses (rule-nesting and the `&` selector) happen to be understood by `styled-components` as well -- meaning you don't have to rearrange RFS's internals at all to do that!

So here's my attempt at converting RFS into JavaScript to make it work. I haven't had any problems with it so far: https://gist.github.com/supposedly/9b9f5de66c2bcbbf5d7469dcec50bfd7

Usage:
```js
import styled from 'styled-components';

import rfs from 'rfs.js';

const Button = styled.a`
  background-color: lightblue;
  ${rfs(`3rem`, `height`)}
  ${rfs.padding(`2rem`)}
  ${rfs.paddingBottom(`0`)}
  ${rfs(`1rem`)} /* font-size, also rfs.fontSize(`1rem`) or rfs(`1rem`, `font-size`) */
`
```
